version: '3'
services:
  api:
    build: api
    depends_on:
      - mongo
    labels:
      - "traefik.backend=api"
      - "traefik.frontend.rule=Host:api.guardian-angel.northeurope.cloudapp.azure.com"

  mongo:
    image: mongo

  ingress:
    image: traefik
    command: --api --docker
    ports: 
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
